gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Build settings
markdown: kramdown
theme: "jekyll-theme-basically-basic"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

layout: "post"
email: "rene_solis2727@hotmail.com"
layout: "about"

