gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/so-simple-theme"

# Build settings
markdown: kramdown
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

layout: "post"
email: "rene_solis2727@hotmail.com"

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
