#gem "github-pages", group: :jekyll_plugins
remote_theme: daattali/beautiful-jekyll
markdown: kramdown

# Your name to show in the footer
author: Rene Solis
title: "Predictors of Marital Infidelity"
description: "Data Science"


 
# Build settings
plugins: # previsously gems
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap


