gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/jekyll-theme-basically-basic"

title: "by Rene Solis"
email: "rsolis@my365.bellevue.edu"
description: "Data Science"

author: 
  name: "Rene Solis" 
  bio: "Data Scientist" 
  location: "Miami, FL" 
  links: 
    - label: "Linkedin"
 
# Build settings
markdown: kramdown
plugins: # previsously gems
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


