remote_theme: daattali/beautiful-jekyll
markdown: kramdown

# Your name to show in the footer
author: Rene Solis
title: "Predictors of Marital Infidelity"
#avatar: "infidelity_project.png"
#round-avatar: true

 
# Build settings
plugins: # previsously gems
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap


