gem "github-pages", group: :jekyll_plugins
remote_theme: "Beautiful Jekyll / Dean Attali"

# Build settings
markdown: kramdown
theme: "jekyll-theme-basically-basic"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

layout: "post"
email: "rene_solis2727@hotmail.com"
layout: "about"

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
