gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/jekyll-theme-basically-basic"

title: "by Rene Solis"
email: "rsolis@my365.bellevue.edu"
contact: "Rene Solis"
description: "Data Science"

author: 
name: "Rene Solis" 
bio: "Data Scientist" 
location: "Miami, FL" 

# Build settings
markdown: kramdown
plugins: # previsously gems
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: pages
    values:
      layout: page
      read_time: true
